### ISSUE TITLE
Regarding the subtheme based on apigee-kickstart

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#384] opened 2020-06-17 18:46 UTC
I went through the documents you have suggested and made a considerable progress.

https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/6dd58a1e93e9d06536b2c79313a93b863610b0e7/themes/custom/apigee_kickstart/README.md#using-drush-to-generate-your-sub-theme

I did it manually but I think i must have missed some thing

Installed the Drush and that made it simple to create a subtheme by running the following command
"drush --include="web/themes/contrib/radix" radix:create "mytheme" --kit=apigee_custom"
 "2/2 [============================] 100%"

I was able to see the theme 

but the issue is i am  unable to see that theme in the Devportal page. Screen Shot below, But able to see the subtheme
![image](https://user-images.githubusercontent.com/56166711/84936545-66911580-b0a8-11ea-8677-e3c938334ff0.png)

Even cleared the Cache too. Can you please guide me through 

Steps Followed:
1. Installed Drush : Drush Commandline Tool 9.7.2
2. Navigate to the site root in your terminal, substituting my-portal with your directory, i.e. cd ~/Sites/my-portal.
3. Ran the Drush command, 
    drush --include="web/themes/contrib/radix" radix:create "mytheme" --kit=apigee_custom

**Comment by cnovak** [comment] 2020-06-18 13:32
Thanks for the clearly written issue. @arshad do you need to clear cache? Looks like everything was done properly.

**Comment by pradeepgorle13** [comment] 2020-06-18 14:10
> Thanks for the clearly written issue. @arshad do you need to clear cache? Looks like everything was done properly.

@cnovak @arshad Just wanted to make sure the steps i have followed. I cleared the cache completely too but it wasn't displaying the theme i have created,

**Comment by shadcn** [comment] 2020-06-22 05:22
@pradeepgorle13 I see a **subtheme** in the screenshot? Is that the theme you created? What happens when you "Install and set as default"?

**Comment by pradeepgorle13** [comment] 2020-06-22 06:56
> @pradeepgorle13 I see a **subtheme** in the screenshot? Is that the theme you created? What happens when you "Install and set as default"?

The "subtheme" was there from before, So i thought that - this is the one of the themes provided by the apigee-kickstart theme. But the theme I created with the steps is "mytheme" which wasn't being applied  which was created using drush commands.

I can let you know by tomorrow about the "subtheme". But Can you please help me out with the "mytheme" in the mean time.

**Comment by shadcn** [comment] 2020-06-22 11:04
@pradeepgorle13 Sure. Can you confirm if "mytheme" was generated successfully? You should see a `mytheme/mytheme.info.yml` file.

**Comment by pradeepgorle13** [comment] 2020-06-22 14:49
> @pradeepgorle13 Sure. Can you confirm if "mytheme" was generated successfully? You should see a `mytheme/mytheme.info.yml` file.

Hey Arshad, Please see the file structure that has been created as following. Also, i just used the Drush command to generate the file structure.


Please find the file contents



Also when i tried to apply the other theme "subtheme" the following error was displayed

**Comment by pradeepgorle13** [comment] 2020-06-25 14:10
@arshad, @cnovak , Any help would be much appreciated. Even tried manually following the steps in "Creating a Sub-theme Manually" from the link 

https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/6dd58a1e93e9d06536b2c79313a93b863610b0e7/themes/custom/apigee_kickstart/README.md#using-drush-to-generate-your-sub-theme

It still doesn't display the theme.

Thanks.,
Pradeep

**Comment by shadcn** [comment] 2020-06-25 14:49
@pradeepgorle13 I attached a new custom theme I generated.

1. Can you extract and place `apigee_new` under `themes/custom`?
2. Then go to Appearance and click Install and set as default.

This should set the new theme as default.

Can you check and let us know if this works?

[apigee_new.zip](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/4832042/apigee_new.zip)

**Comment by pradeepgorle13** [comment] 2020-06-25 17:23
> @pradeepgorle13 I attached a new custom theme I generated.
> 
> 1. Can you extract and place `apigee_new` under `themes/custom`?
> 2. Then go to Appearance and click Install and set as default.
> 
> This should set the new theme as default.
> 
> Can you check and let us know if this works?
> 
> [apigee_new.zip](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/4832042/apigee_new.zip)

@arshad Thanks for the suggestion and the zip folder. I tried as you suggested. I copied the folder in the themes/custom


But the theme is not displayed. Used the Cognito Window (No Cahe on browser side). Also did a "drush cache:rebuild".
Please find the below screen shot for undisplayed theme in the list of uninstalled themes. Clarifying that, it is not even present in the insralled themes too. 


Also find the contects in the apigee_new.info.yml file

**Comment by shadcn** [comment] 2020-06-25 18:19
@pradeepgorle13 Hmm weird. Can you reproduce the same issue on a clean kickstart install?

**Comment by pradeepgorle13** [comment] 2020-06-25 18:35
@arshad I did that too day before yesterday. We reinstalled apigee-devportal on another server and created new theme(using drush) with name "mytheme" and also copied the "apigee_new" theme today. But, I am unable to see the theme under appearence tab.

**Comment by cnovak** [comment] 2020-06-25 22:21
Could it be file permissions? Can the webserver/PHP read these files?

**Comment by pradeepgorle13** [comment] 2020-06-26 00:21
@cnovak @arshad 

This is for the radix theme that i have verified.


Please find the themes permissions. I have created two themes with drush and two themes by copying in there from my computer.

Am i missing anything here, Can you  please let me know. I can get an webex for your verification too, if required.

Thanks.,

**Comment by pradeepgorle13** [comment] 2020-06-26 15:49
> @cnovak @arshad
> 
> This is for the radix theme that i have verified.
> 
> 
> Please find the themes permissions. I have created two themes with drush and two themes by copying in there from my computer.
>
> Am i missing anything here, Can you please let me know. I can get an webex for your verification too, if required.
> 
> Thanks.,

@arshad @cnovak 

The issue got resolved guys. Thanks for your input, it is to work with permissions only. 
How i resolved this
1. I took a server out side of the network and when i used the drush command and created the theme it worked perfectly with the same access permissions as it was in my organization.
2. So i was pretty sure that, there must be some issue within the organization, So I started applying all the security from 750(Chmod which compares with the existing themes)
3. Laborious, but went one by one(trail and error) up above the order till 775 and suddenly it worked. So, I feel that when ever we are creating the subtheme on-prem, I suggest it to be with
                       " chmod -R 775 mytheme "
   

Can you please add this to the documentation, so that others will not get this sort of issue. 
Thanks a lot guys.

**Comment by shadcn** [comment] 2020-06-29 13:12
@pradeepgorle13 This is great that you figured it out. Thanks for letting us know. 

Drupal covers file permissions in the official doc here: https://www.drupal.org/node/244924

I'm going to close this issue. Feel free to re-open or create a new one if you have any other questions.

Thanks

**Closed as completed by shadcn** 2020-06-29 13:12 UTC
Labels: bug
