### ISSUE TITLE
Monetization setup is not completed in Kickstart installation

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#309] opened 2020-01-31 17:49 UTC
# Description 

When installing Kickstart, you can enable prepaid balance topup if it is a monetization enabled org:

<img width="716" alt="kickstart-install-configure-m10n" src="https://user-images.githubusercontent.com/613093/73500837-a7e28c00-4378-11ea-8b8e-f025fff86f4b.png">

Once installed, the prepaid balances still does not show up on the balances page until you go to the requirements module and finish the requirements steps:

1. Add credit products
2. Add Credit product type
3. Commerce store
4. Add to Cart form display
5. Payment gateway

However, the requirements steps 1 -4 do not have anything needed to do but click a button. Only the Payment gateway requirement has any need to fill out a form. 

# Issues
1.  Why doesn't the Kickstart monetization take care of 1-4 for me instead of making me need to click through buttons in the requirement module steps? It does not ask for any additional information.
2. The monetization installer screen also does not say anything about needing to finish steps later or link to documentation on what is left to do.

**Comment by shadcn** [comment] 2020-02-03 05:24
Hmm it looks like there's a regression somewhere. Step 1, 2 and 3 are definitely covered in the installation. 

See https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/8.x-1.x/apigee_devportal_kickstart.install#L128

Step 4 should be easy to add. Step 5 will require a bit more work.

**Comment by cnovak** [comment] 2020-02-04 19:57
We don't need to automate step5, just add a note in the installer telling user they will need to configure a payment gateway w/a link to our docs.   In Drupal 7 if you did not install a payment gateway the system would still work FYI, just had no way to charge the user. Would be good to see how system behaves w/out payment gateway configured to make sure system does not crash, etc.

**Comment by shadcn** [comment] 2020-02-12 09:00
@cnovak I just ran an installation again to check this and Step 1 to 4 is covered by kickstart. The "Add to Cart form display" is handle via config here: `https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/8.x-1.x/modules/custom/apigee_kickstart_m10n_add_credit/config/install/core.entity_form_display.commerce_order_item.add_credit.add_to_cart.yml`

As for the payment gateway, you need this to checkout.

![Order_information___Apigee_Kickstart_-_Mozilla_Firefox](https://user-images.githubusercontent.com/124599/74318992-a57c2b00-4d97-11ea-8fdd-630b87d7440b.jpg)

**Comment by arlina-espinoza** [comment] 2020-02-22 00:23
@cnovak I think this should also be fixed by #323  and https://github.com/apigee/apigee-m10n-drupal/pull/223.

**Comment by shadcn** [comment] 2020-02-28 05:51
https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/323 and https://github.com/apigee/apigee-m10n-drupal/pull/223 have been merged.

We have a follow-up ticket in `apigee_m10n` to create a test payment gateway: https://github.com/apigee/apigee-m10n-drupal/issues/227

I'm going to mark this ticket as done. Feel free to re-open if not.

Thank you.

**Closed as completed by shadcn** 2020-02-28 05:51 UTC
Labels: enhancement
