### ISSUE TITLE
Unable to connect SSO Org, Oauth configured with private file. still errors when i click on Apps

### ISSUE THREAD

**Issue by rengan76** [apigee/apigee-devportal-kickstart-drupal#248] opened 2019-08-11 16:42 UTC
I have configured Oauth2 got the oauth token. our Apigee edge is SSO enabled.  After connection sucuessful. When i click on the APPS. This is what i see always

TypeError: Return value of Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache::getEntityId() must be of the type string, null returned in Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache->getEntityId() (line 40 of C:\xampp\htdocs\portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\DeveloperIdCache.php) #0 C:\xampp\htdocs\portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\EntityIdCache.php(74): Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache->getEntityId(Object(Apigee\Edge\Api\Management\Entity\Developer)) #1 [internal function]: Drupal\apigee_edge\Entity\Controller\Cache\EntityIdCache->Drupal\apigee_edge\Entity\Controller\Cache\{closure}(Object(Apigee\Edge\Api\Management\Entity\Developer)) #2 C:\xampp\htdocs\portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\EntityIdCache.php(73): array_map(Object(Closure), Array) #3 C:\xampp\htdocs\portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\EntityCache.php(94): Drupal\apigee_edge\Entity\Controller\Cache\EntityIdCache->saveEntities(Array) #4

**Comment by arunz6161** [comment] 2019-08-12 01:04
@rengan76 the problem you are seeing is similar to #245 . As a workaround, could you drop the database and recreate a new and let us know if that helps get around the problem. As per  #245 , the issue is caused because of an invalid value for Apigee MGMT API endpoint.

**Comment by rengan76** [comment] 2019-08-12 09:40
@arunz6161. The connection success with oauth token still the same error with sso enabled apigee  edge. But when i try with my evaluation account on apigee edge everything working good. When it tries to connect to sso enabled apigee edge the problem  exists. But you can say you need proper devportal credentials yes i do have.

**Comment by rengan76** [comment] 2019-08-12 09:44
The 245 issue is different. We can skip the installation and configure it on the admin it works. We can clear flush caches and change db if wanted on the settings.php we can remove the cache config with db settings and change. My case is totally different than 245 case. I bet no one tested with sso enabled apigee edge.  I have tried with evaluation apigee edge connection it works charming.  Someone has to look at this issue because its blocking my work.

**Comment by arunz6161** [comment] 2019-08-12 23:45
Resolved by https://github.com/apigee/apigee-edge-drupal/issues/253

**Closed as completed by arunz6161** 2019-08-12 23:45 UTC
Labels: bug
