### ISSUE TITLE
Form validation error for input type checkbox/radio

### ISSUE THREAD

**Issue by ibilo** [apigee/apigee-devportal-kickstart-drupal#690] opened 2024-05-10 12:55 UTC
I added a new checkbox field to the registration form and made it required.
If all the required fields are filled except the checkbox, you should get a message like 
`"Please check this box if you want to proceed"`, 
but in our case, we get an error in the developer tools like 
`"An invalid form control with name='...' is not focusable."`.
![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/65223659/a0a0f435-84b0-4839-86a0-5996ed001abb)

This works if this part of the CSS styles is disabled:
https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/4b4a12502df7cb726799bd5c19af6dd13a8ff589/themes/custom/apigee_kickstart/assets/css/apigee-kickstart.style.css#L18779
![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/65223659/32b21f2d-4a97-45ad-9e1d-4b8975111503)

![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/65223659/b6c2df82-fadb-409d-a207-37b7adc9db37)

So any new fields with the type of checkbox or radio button will not be validated with "display: none" style.

**Comment by kedarkhaire** [comment] 2024-05-13 11:33
Hi @ibilo 
Thanks for sharing the issue you faced, here we are considering the steps you took were via custom module and you altered this specific form, added this new checkbox field and a default form 'required' validation is set for it.
Post that you are facing the above behavior.

Do let us know, if our assumption is right or if any other steps were taken, this will be helpful for checking the issue further.

Also do mention, the versions used.

Thanks!

**Comment by ibilo** [comment] 2024-05-14 13:58
Drupal Version - 10.2.5
Installation profile - Apigee Developer Portal Kickstart
Theme - Apigee Kickstart (default theme)

I am using the Apigee Kickstart as the default theme, and I didn't install any custom modules.
I added a field from the admin panel by this URL path: "/admin/config/people/accounts/fields". 
Everything works fine if switch the Apigee Kickstart theme to let's say, Olivero. 
In your theme you hide the default inputs by replacing them with SVG icons and in this case the validation doesn't work because the default input, in my case a checkbox, is not displayed on the UI.

**Comment by kedarkhaire** [comment] 2024-06-19 05:57
Hi @ibilo 
I checked the above-mentioned with provided steps, I am not able to reproduce this with the said versions.
If there are any other points which we need to follow, to replicate the issue, feel free to share.
Thanks!

**Comment by kedarkhaire** [comment] 2024-07-01 06:35
Hi @ibilo 
Closing this issue, as we are not able to replicate it and considering it was due to another custom work as there is no reply for any other steps which leads to this issue.
Anyways, if you found the steps to replicate the issue, feel free to reopen the ticket.
Thanks!

**Closed as completed by kedarkhaire** 2024-07-01 06:35 UTC
