### ISSUE TITLE
Install the Drupal in docker stuck on 98%

### ISSUE THREAD

**Issue by aryaroudi** [apigee/apigee-devportal-kickstart-drupal#347] opened 2020-04-02 16:43 UTC
**Describe the bug**
I set up my environment with Lando and tried on 2 different MacBook Pro laptops and the installation stuck on 98% and not going further.
**To Reproduce**
Do the `lando start`
Open the environment in the browser (It will redirect you to Install page)
Enter the database details

**Expected behavior**
There should be an error to show why it stuck there

**Screenshots**
![image](https://user-images.githubusercontent.com/43990136/78275054-66ee2b80-7511-11ea-9859-1fc4c5f2e137.png)

**Additional context**
If I install the drupal bu `drush` it works fine btw

**Version Info**
Drupal: 8.8
Lando: 3.0.0-rrc.2
MySql: 8.0.19

**Comment by cnovak** [comment] 2020-04-06 16:24
@aryaroudi could you share your lando config with us to help validate?

**Comment by shadcn** [comment] 2020-04-13 08:08
@aryaroudi did you figure this out? 

I just tested with the following `.lando.yml` config and it worked. 

```yml
name: kickstart

recipe: drupal8

config:
  webroot: web
  php: 7.3
  database: mariadb
```

If you could post your lando config, we can test it.

**Comment by aryaroudi** [comment] 2020-04-17 11:59
hey @cnovak yes sure:

```
name: d8-composer-verify
recipe: drupal8
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
config:
  drush: "*"
  webroot: web
  database: 'mysql:8.0.19'
  config:
    database: config_lando/my-custom.cnf
```
not yet, I'm just continued to install it by `drush si` and that way it works, anyway I guess it won't be a concern for me as we need to put the whole process in a CI/CD pipeline and we need to install it by CLI but just shared it in case someone faces the same issue in the web console

**Comment by shadcn** [comment] 2020-04-22 05:29
Thanks for posting the config file. I just tested it and seems to be working. Weird. I'll ask someone else to try this and let you know.

**Comment by shadcn** [comment] 2020-04-24 10:14
@aryaroudi We tested this on another clean lando install with the provided config and could not reproduce this. 

Since this is not a blocker for you anymore, I'm going to go ahead and close this.

Feel free to re-open if this is still an issue. Thank you.

**Closed as completed by shadcn** 2020-04-24 10:14 UTC
Labels: bug
