### ISSUE TITLE
Unable sync developers from apigee edge to drupal 8

### ISSUE THREAD

**Issue by rengan76** [apigee/apigee-devportal-kickstart-drupal#249] opened 2019-08-12 00:26 UTC
After OAuth connection successful and got the OAuth.dat token. When try to click on the APPS button errors and when try to sync developers below is the error

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /batch?id=5&op=do_nojs&op=do
StatusText: OK
ResponseText:

**Comment by arunz6161** [comment] 2019-08-12 01:05
@rengan76 this issue very likely has the same root cause as #248 . Lets keep this open to see if the issue persists after solving #248

**Comment by rengan76** [comment] 2019-08-12 09:07
Thanks Arun. I did that 20 times.  As i said for me connection success at OAuth. The solution to 245 is not to install database skip the apigee installation and then do the oauth or basic connection on configuration.  But my case is oauth token is there but errors on the apps with entity id.

**Comment by arunz6161** [comment] 2019-08-12 23:45
Resolved by https://github.com/apigee/apigee-edge-drupal/issues/253

**Closed as completed by arunz6161** 2019-08-12 23:45 UTC
Labels: bug
