### ISSUE TITLE
Patching fails when installing through composer.

### ISSUE THREAD

**Issue by simantstha** [apigee/apigee-devportal-kickstart-drupal#565] opened 2022-06-28 22:44 UTC
![image](https://user-images.githubusercontent.com/30699044/176316640-22d9c86a-9996-4a03-9589-11804a6bb71c.png)

**Comment by shishir-intelli** [comment] 2022-07-01 09:51
Duplicate of #568

**Closed as completed by shishir-intelli** 2022-07-01 09:51 UTC
