### ISSUE TITLE
Mismatched entity and/or field definitions

### ISSUE THREAD

**Issue by cen1** [apigee/apigee-devportal-kickstart-drupal#586] opened 2022-10-13 20:44 UTC
## Description

In the status report page I see the following error:

Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.
Product variation
The Price range field needs to be updated.
Product
The This is an Apigee add credit product field needs to be updated.

## Steps to Reproduce
I am not 100% sure when or how this happened. It might have appeared after upgrading drupal core and it's dependencies. We are on version 9.4.8.

I also tried 9.5.0-beta2 but the error stays. I restored the database to before upgrade so current state is 9.4.8.

## Notes
Everything seems to still work as expected but the error makes me uneasy.

I assume something got broken with the database schema? I think I'll just try to reinstall the apigee module that is responsible for products (is that "Apigee Monetization Add Credit"?) but I'd also welcome any other suggestions.

## Version Info
2.1.0

**Comment by shishir-intelli** [comment] 2022-10-14 05:36
HI @cen1 
Thank you for reporting this issue.

Could you please share with us the output of this command: `composer show` to investigate this issue.

**Comment by cen1** [comment] 2022-10-14 06:04
[composer_show.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/9782912/composer_show.txt)

**Comment by cen1** [comment] 2022-10-14 10:08
Reinstalling Apigee Monetization Add Credit solved the problem.

**Comment by shishir-intelli** [comment] 2022-10-14 11:21
Not able to reproduce the issue.

However, while installing 9.4.8 with PHP 8.1.10, I found some issues while enabling the add credit module, we are investigating it.
We will keep you posted on further updates.

**Comment by shishir-intelli** [comment] 2022-10-17 05:54
Hi @cen1 
We tried to reproduce this issue but were not able to reproduce.

The above mentioned error by me (```while installing 9.4.8 with PHP 8.1.10```) was due to some local system issue.
Closing this issue for now please feel free to re-open for any further issue.

**Closed as completed by shishir-intelli** 2022-10-17 05:54 UTC
Labels: bug
