### ISSUE TITLE
Drupal 8 Apigee Kickstart HTTPS issue

### ISSUE THREAD

**Issue by BillMarx** [apigee/apigee-devportal-kickstart-drupal#425] opened 2020-09-16 21:17 UTC
Hi,
I have a drupal 8 server in AWS loaded with the Apigee kickstart.  I recently added a certificate and configured for https.  The main screen works but all the other links break as they refer back to http.  I have tried all of the suggestions in https://www.drupal.org/https-information as far as .htaccess rewrite rules and settings.php.  This breaks the site with too many redirect messages.  Any assistance would be approceiated. 

Thanks!!

**Comment by arlina-espinoza** [comment] 2020-09-16 21:50
Hi @BillMarx ,

Most likely the issue is that the drupal site is served behind a load balancer / reverse proxy. In this setup the drupal site might not actually _know_ that the content is being requested via https and thus show all links as http. In D7 it was an easy fix, as you could easily configure  `$base_url`. However, for D8 you'll need to configure some things in your settings.php file, something like:

```
$settings['reverse_proxy'] = TRUE;
$settings['reverse_proxy_addresses'] = ['1.2.3.4', ...];
// See https://symfony.com/doc/current/deployment/proxies.html.
$settings['reverse_proxy_trusted_headers'] = \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_ALL
```

Take a look at these couple of articles for more details:
- Drupal core docs: [Using a load balancer or reverse proxy](https://www.drupal.org/node/425990)
- [Drupal 8 and reverse proxies: The $base_url drama](https://medium.com/@lmakarov/drupal-8-and-reverse-proxies-the-base-url-drama-c5553cbc9a3e)

**Comment by arlina-espinoza** [comment] 2020-09-18 21:15
Closing, but feel free to reopen if there are further questions.

**Closed as completed by arlina-espinoza** 2020-09-18 21:15 UTC
Labels: support request
