### ISSUE TITLE
Kickstart Installation - Enabling Demo Content throwing error

### ISSUE THREAD

**Issue by raakesh-blokhra** [apigee/apigee-devportal-kickstart-drupal#450] opened 2021-01-26 18:37 UTC
## Description
While installing a new setup using Apigee Kickstart, got an error on the lasts step - enable demo content. Install failed. However refreshing the page fixed the install and installed demo content without an issue. Can someone please check if this is happening on their instances also or only on my local XAMPP setup?

## Steps to Reproduce
1. Run composer install for a fresh install (composer create-project apigee/devportal-kickstart-project:8.x-dev <instanceName>
2. Point to browser ( <instanceName>/web/ )and continue installation till last page (enable demo content)
3. Check the checkbox for Enable Demo Content and click Continue.
4. Page displays an error.
5. Refresh the page and it takes you to the homepage

## Actual Behavior
Getting an error message. 

## Expected Behavior
We should not receive any error messages. Demo content should be created by default and the user should be taken to the homepage.

## Notes
I tried this twice and got the error. I am not sure if this is specific to my local environment. Would like someone to check this out and close the ticket if no errors encountered.

## Version Info
Drupal: 8.9.13
Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/7.4.13
DB: 5.5.5-10.4.17-MariaDB
PHP: 7.4.13

**Comment by cnovak** [comment] 2021-01-26 18:59
What is the error that you see?

**Comment by raakesh-blokhra** [comment] 2021-01-27 06:29
> What is the error that you see?

Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY': INSERT INTO {taxonomy_term_data} (tid, revision_id, vid, uuid, langcode) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array ( [:db_insert_placeholder_0] => 3 [:db_insert_placeholder_1] => 2 [:db_insert_placeholder_2] => forums [:db_insert_placeholder_3] => 40d3bba3-edec-4794-9481-3c4e21cdd396 [:db_insert_placeholder_4] => en ) in Drupal\Core\Database\Connection->handleQueryException() (line 698 of xxxxxxxxxxxxxxxxxxxx\web\core\lib\Drupal\Core\Database\Connection.php).

**Comment by damianrobinson** [comment] 2021-02-12 17:46
I can also replicate the error - seems to fail on the same entity:

```
 [error]  Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY': INSERT INTO {taxonomy_term_data} (tid, revision_id, vid, uuid, langcode) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array
(
    [:db_insert_placeholder_0] => 3
    [:db_insert_placeholder_1] => 2
    [:db_insert_placeholder_2] => forums
    [:db_insert_placeholder_3] => 40d3bba3-edec-4794-9481-3c4e21cdd396
    [:db_insert_placeholder_4] => en
)
 in Drupal\Core\Database\Connection->handleQueryException() (line 698 of xxxx\core\lib\Drupal\Core\Database\Connection.php).
```

**Comment by shishir-intelli** [comment] 2021-05-14 10:06
I was not able to reproduce this issue.

This seems to be some DB connection issue may be due to glitch in installation.
Closing this ticket for now. Feel free to reopen in case you are still having any issues.

**Closed as completed by shishir-intelli** 2021-05-14 10:06 UTC
Labels: bug
