### ISSUE TITLE
Needed to Provide "Add API Doc" option to the Authenticated user or specific User

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#396] opened 2020-07-20 16:08 UTC
Hi Team,

The Requirement is as follows:
        -  Apart from the administrator, an user should be able to add the Open API Spec using the "Add API Doc"
I followed the following steps
1. I added a role with the name
    
![image](https://user-images.githubusercontent.com/56166711/87958533-a66c6380-ca7f-11ea-94e4-dc0c3c291f7b.png)

![image](https://user-images.githubusercontent.com/56166711/87958610-bd12ba80-ca7f-11ea-8cbc-f641dce95117.png)

2. Then I added the API Doc related access to that role and saved it

![image](https://user-images.githubusercontent.com/56166711/87958852-0b27be00-ca80-11ea-80be-3d9f22e04a41.png)

3.  Then add that role (MyRole) to the user and saved it.

![image](https://user-images.githubusercontent.com/56166711/87959172-77a2bd00-ca80-11ea-8cf9-116bc3d97ae6.png)

![image](https://user-images.githubusercontent.com/56166711/87959362-c2bcd000-ca80-11ea-93fe-50e1911fb5cb.png)

4. Then, I logged into it as a federated user using Ping

![image](https://user-images.githubusercontent.com/56166711/87959465-eed85100-ca80-11ea-82e9-676c696cf609.png)

5. I didn't see any place where i can publish the API for that user

![image](https://user-images.githubusercontent.com/56166711/87959905-8e95df00-ca81-11ea-8194-f72425dc2504.png)

Please let me know if i have missed any steps or this is what i have gone through the roles and had a basic understanding of it.

Thanks.,
PRadeep

**Comment by kiranjyoth** [comment] 2020-07-20 16:33
@pradeepgorle13 
Can you access /admin/content/apis page using this user role ? If so, you have to set a few more permissions. 
![image](https://user-images.githubusercontent.com/1490213/87962374-f04b4e80-ca6b-11ea-8017-1c90467254f2.png)
![image](https://user-images.githubusercontent.com/1490213/87962411-fe00d400-ca6b-11ea-9b97-c01494f2ddcf.png)
Apart from these, you may have to check permissions on taxonomy, media, etc. based on your configuration. 
Thanks

**Comment by pradeepgorle13** [comment] 2020-07-20 17:31
> @pradeepgorle13
> Can you access /admin/content/apis page using this user role ? If so, you have to set a few more permissions.
> ![image](https://user-images.githubusercontent.com/1490213/87962374-f04b4e80-ca6b-11ea-8017-1c90467254f2.png)
> ![image](https://user-images.githubusercontent.com/1490213/87962411-fe00d400-ca6b-11ea-9b97-c01494f2ddcf.png)
> Apart from these, you may have to check permissions on taxonomy, media, etc. based on your configuration.
> Thanks

@kiranjyoth 

I checked for that url you have passed, I see as unauthorized. So Can you please let me know what other access I need to give for the user.
  
![image](https://user-images.githubusercontent.com/56166711/87967686-306ef900-ca8d-11ea-82fa-ab530ad153c2.png)


![image](https://user-images.githubusercontent.com/56166711/87966073-b8073880-ca8a-11ea-9856-1abfd7a92b5b.png)

What are the other options i need to check for giving only the add access?

**Comment by kiranjyoth** [comment] 2020-07-20 20:06
@pradeepgorle13 You may have to add access to 'content overview page'. If you don't want to give access here, you can add API docs from here --  '/admin/content/api/add' (for API Catalog 2.1 ) 
' node/add/apidoc ' (for API catalog 2.2) 
![image](https://user-images.githubusercontent.com/1490213/87981001-58f4f400-ca89-11ea-88de-40eab38f5c2e.png)

**Comment by pradeepgorle13** [comment] 2020-07-20 21:06
> @pradeepgorle13 You may have to add access to 'content overview page'. If you don't want to give access here, you can add API docs from here -- '/admin/content/api/add' (for API Catalog 2.1 )
> ' node/add/apidoc ' (for API catalog 2.2)
> ![image](https://user-images.githubusercontent.com/1490213/87981001-58f4f400-ca89-11ea-88de-40eab38f5c2e.png)

Hi Kiran,

I added as you mentioned previously
 - I enabled the "Access content overview page"
 - I enabled the "use the toolbar"

When i selected the "Administer API Catalog", I am able to see the "Add API doc". But it is givving access to Edit/delete other API's.
![image](https://user-images.githubusercontent.com/56166711/87984775-7be2d080-caa8-11ea-9e77-ef0805fbc2cd.png)

Also the Content Tab and the content info are being displayed
![image](https://user-images.githubusercontent.com/56166711/87985129-16dbaa80-caa9-11ea-8a91-c77200231654.png)


But when i disabled the "Administer API Catalog" and enable the create New API Docs as shown below

![image](https://user-images.githubusercontent.com/56166711/87984861-a59bf780-caa8-11ea-8249-7c98ce990f0d.png)

I am unable to see the add API doc anymore but only content.
![image](https://user-images.githubusercontent.com/56166711/87986029-9453ea80-caaa-11ea-80a9-fe81919c61a6.png)

As you already mentioned that when i used '/admin/content/api/add' it is enabled to add the API Doc.

But the requirement was to get the user to add the API Doc when they go to Content>add API Doc and without the display of content and enabling that particular user to add his OAS Document and edit it (Not allowing him to change/delete the other OAS docs).

Sorry for the long explanation but wanted to throw out what i have tried to do.

Thanks.,
Pradeep

**Comment by kiranjyoth** [comment] 2020-07-20 22:11
Hello Pradeep, 

I have setup a new instance with the configuration and requirement you described, and **I can confirm** that without enabling **Administer API catalog** permission, API catalog is not accessible to a user, even if the role is configured to add API docs. 
This seems to be a bug with the module in permissions and role matrix. 

As Apigee API Catalog module is now updated to version 8.2.2, it's best to upgrade now and configure these permissions. The new version for API catalog also provides much more flexibility around search, node and form display. This being a content entity it will now inherit all features that other modules provide without having to customize your instance. 

Thanks

**Comment by pradeepgorle13** [comment] 2020-07-20 22:23
> Hello Pradeep,
> 
> I have setup a new instance with the configuration and requirement you described, and **I can confirm** that without enabling **Administer API catalog** permission, API catalog is not accessible to a user, even if the role is configured to add API docs.
> This seems to be a bug with the module in permissions and role matrix.
> 
> As Apigee API Catalog module is now updated to version 8.2.2, it's best to upgrade now and configure these permissions. The new version for API catalog also provides much more flexibility around search, node and form display. This being a content entity it will now inherit all features that other modules provide without having to customize your instance.
> 
> Thanks

Great.. Thanks for the Information. May I know - how i can update the latest version of the APIGEE API Catalog module.
Please note that we have a Firewall which doesn't enable us to upgrade through portal/through internet. Is there a way where i can download and them upgrade it on the boxes. And the locations where i can copy those under /var/www/devportal/ folder.

**Comment by kiranjyoth** [comment] 2020-07-20 23:12
@pradeepgorle13 here is the download link https://www.drupal.org/project/apigee_api_catalog/releases/8.x-2.2
Recommended installation is using composer.  

Our approach for working within a firewall is to download the updated module locally, commit to the repo and deploy it on the server using CI. But if thats not an option, you may download the zip/tar file and unzip it, replace the older one with new version. 

Once you do this, you will have to run `drush updb` for performing schema updates. **Backups and lower environments are highly recommended**, as this may have breaking changes.

> The update from 8.x-1.x to 8.x-2.x will try to recreate any custom fields that were added to the API Doc custom entity onto a new "API Doc" node bundle, migrate data, and delete all API Doc custom entities and definitions. It is highly recommended to test on a development environment before running it in production. It is necessary to run database updates for this release.

Thanks

**Comment by pradeepgorle13** [comment] 2020-07-20 23:23
@kiranjyoth Thanks for the suggestion will go through the upgrade process and will let you know. So i am assuming that 8.x-2.2 version is a stable version

**Comment by kiranjyoth** [comment] 2020-07-21 05:08
Correct, 8x.2.2 is the latest stable one release July 14th and tagged as recommended by the maintainer.

**Comment by arunz6161** [comment] 2020-07-21 19:00
To do: Document upgrade instructions for users behind firewall.

**Comment by pradeepgorle13** [comment] 2020-07-22 13:12
> Correct, 8x.2.2 is the latest stable one release July 14th and tagged as recommended by the maintainer.

Will try and let you know.. Thanks @kiranjyoth

**Comment by pradeepgorle13** [comment] 2020-07-25 00:51
> drush updb

@kiranjyoth 
I just downloaded the Zip folder and extracted it. I copied the apigee_api_catalog module and restarted the server. Then ap per your instruction I did the "drush updb". Please find the screenshot below
![image](https://user-images.githubusercontent.com/56166711/88445186-1c116000-cdef-11ea-8f90-baa065a3c94a.png)

Then I restarted the server But I am getting the following error
![image](https://user-images.githubusercontent.com/56166711/88445231-5549d000-cdef-11ea-9b59-49fa0ce8db00.png)

Can you please suggest me the way forward.
,

**Comment by kiranjyoth** [comment] 2020-07-27 04:55
@pradeepgorle13 looks like your install is not able to find the updated module. And from your screenshot I see no pending updates, which means the module is not updated. So I decided to attempt this on an older instance this weekend as I had some time and seemed like a fun challenge. I'm attaching a video of the upgrade attempt I did here. I will write a blog post about this sometime next week in more details.  

[![Apigee Kickstart - API Catalog Upgrade](https://j.gifs.com/OMnmnr.gif)](https://youtu.be/FZIjcpQOgIU)

**Watch it here** https://youtu.be/FZIjcpQOgIU

This leads to the question on how to upgrade if you are behind firewall in your case. We can simply run 
`composer update` 
and download packages locally, commit it to git repository and deploy on server. Then you can run database updates and perform other actions needed.  As @arunz6161 identified, we should document these steps. I will work on finding if we can find a better way to automate this here . https://github.com/apigee/devportal-kickstart-drupal-ansible-installer

**Comment by pradeepgorle13** [comment] 2020-07-27 17:28
> @pradeepgorle13 looks like your install is not able to find the updated module. And from your screenshot I see no pending updates, which means the module is not updated. So I decided to attempt this on an older instance this weekend as I had some time and seemed like a fun challenge. I'm attaching a video of the upgrade attempt I did here. I will write a blog post about this sometime next week in more details.
> 
> [![Apigee Kickstart - API Catalog Upgrade](https://camo.githubusercontent.com/bf57cfdaf30ae4a35563859827ce8ac074b361b6/68747470733a2f2f6a2e676966732e636f6d2f4f4d6e6d6e722e676966)](https://youtu.be/FZIjcpQOgIU)
> 
> **Watch it here** https://youtu.be/FZIjcpQOgIU
> 
> This leads to the question on how to upgrade if you are behind firewall in your case. We can simply run
> `composer update`
> and download packages locally, commit it to git repository and deploy on server. Then you can run database updates and perform other actions needed. As @arunz6161 identified, we should document these steps. I will work on finding if we can find a better way to automate this here . https://github.com/apigee/devportal-kickstart-drupal-ansible-installer

@kiranjyoth Thanks for the response. It was very helpful. So I have asked my firewall team to open the network for the drupal site for a Day. Then as per the instruction in the Drupal site 
https://www.drupal.org/project/apigee_api_catalog/releases/8.x-2.2
I used the command
![image](https://user-images.githubusercontent.com/56166711/88572190-c4504000-d00c-11ea-808c-5709e5ac6258.png)

Just got little bit further now
![image](https://user-images.githubusercontent.com/56166711/88572894-eeeec880-d00d-11ea-975a-f24e3d68398c.png)

Any suggestions. This is a Dev environment

**Comment by kiranjyoth** [comment] 2020-07-27 17:42
@pradeepgorle13 great, if its dev and you have backed up, please run `composer update`. or if you want to just focus on updates for kickstart use `composer update drupal/apigee_devportal_kickstart`. API catalog 2.2 is available only for kickstart 1.7 and hence the requirement lock.

**Comment by pradeepgorle13** [comment] 2020-07-27 21:13
> @pradeepgorle13 great, if its dev and you have backed up, please run `composer update`. or if you want to just focus on updates for kickstart use `composer require drupal/apigee_devportal_kickstart`. API catalog 2.2 is available only for kickstart 1.7 and hence the requirement lock.

@kiranjyoth Thanks for the response
updated the apigee kick start as well as the catalog
![image](https://user-images.githubusercontent.com/56166711/88591326-2cf9e580-d02a-11ea-9010-a015a324aed2.png)

Then ran the updb too
![image](https://user-images.githubusercontent.com/56166711/88592060-60893f80-d02b-11ea-8642-e28b918d54dd.png)

Then i restarted the server.

Then I tried to see which versions are there in the updates. Kickstart has got updated to 1.17 and  catalog still shows 1.2(is this 2.2 ???) because it used to show 1.1(screen shot attached).
![image](https://user-images.githubusercontent.com/56166711/88592304-cd043e80-d02b-11ea-9094-a4e96df58caf.png)
Before update
![image](https://user-images.githubusercontent.com/56166711/88592702-6e8b9000-d02c-11ea-8d72-0a0fc8210bee.png)

But i am not seeing the "Apigee API Catalog" section under permissions
![image](https://user-images.githubusercontent.com/56166711/88593264-481a2480-d02d-11ea-9056-21c5c97719b2.png)

**Comment by kiranjyoth** [comment] 2020-07-27 21:39
@pradeepgorle13 seems like the catalog is not updated. Check your composer file at web/profiles/contrib/apigee_devportal_kickstart/composer.json . The following is mine. If it easier for a quick call, please use this and chat. https://drift.me/stratus-support/ 
```  
"require": {
    "cweagans/composer-patches": "^1.6.5",
    "drupal/admin_toolbar": "^2.0",
    "drupal/adminimal_admin_toolbar": "^1.9",
    "drupal/apigee_api_catalog": "^2.2",
    "drupal/apigee_edge": "^1.10",
    "drupal/better_exposed_filters": "^3.0@alpha",
    "drupal/default_content": "^1.0@alpha",
    "drupal/email_registration": "^1.0@RC",
    "drupal/fontawesome": "^2.12",
    "drupal/paragraphs": "^1.6",
    "drupal/pathauto": "^1.6",
    "drupal/radix": "^4.8"
},
```

**Comment by pradeepgorle13** [comment] 2020-07-28 02:32
@kiranjyoth you were correct. It is still pointing to 1.0. Please see the screenshot below
![image](https://user-images.githubusercontent.com/56166711/88612219-b32d2080-d058-11ea-9dae-5f112f3429b2.png)
Will connect with you tomorrow through the chat link you have sent

**Comment by pradeepgorle13** [comment] 2020-07-29 22:34
@kiranjyoth @cnovak @earth2marsh 
Thanks Kiran for spending more than two hours and guiding me through the issue. Really appreciate your efforts in getting this issue resolved.

Thanks.,
Pradeep

**Comment by cnovak** [comment] 2020-07-30 03:29
Thank you @kiranjyoth for giving such great help!

**Comment by cnovak** [comment] 2020-12-03 22:58
I will close this issue, but please comment if there is anything left to do.

**Closed as completed by cnovak** 2020-12-03 22:58 UTC
Labels: bug
