### ISSUE TITLE
Search is not working for Entity types (API Docs)

### ISSUE THREAD

**Issue by mrdhanasekaran89** [apigee/apigee-devportal-kickstart-drupal#298] opened 2020-01-07 06:25 UTC
Hi Team,

When we search API doc items in Search form, its not displaying search result from API doc.

How to Reproduce:
----------------------
1. Go to Apigee portal, Enter the keyword which is the title/description of any API doc and click Enter.
2. Search result will display in a page. But this result is not having API doc items.

Expected behavior:
----------------------
Search should pull contents from Entities also. As of now, its pulling contents only from nodes and users.

Screenshots:
---------------
API doc listing page:
![image](https://user-images.githubusercontent.com/50447235/71872814-84467000-3143-11ea-9aa6-3720be2adeb9.png)

Search form:
![image](https://user-images.githubusercontent.com/50447235/71872839-988a6d00-3143-11ea-9525-38cf5727db8b.png)

Search Results:
![image](https://user-images.githubusercontent.com/50447235/71872874-af30c400-3143-11ea-8694-b91f23530a80.png)

Search configuration: (URL: /admin/config/search/pages)
![image](https://user-images.githubusercontent.com/50447235/71873082-4bf36180-3144-11ea-93de-817ada4da279.png)

Can you please fix the issue and update the distribution asap OR let me know how to solve this issue.

Thanks
M.Dhanasekaran

**Comment by shadcn** [comment] 2020-01-07 13:14
@mrdhanasekaran89 this is a duplicate of https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/289. I'm going to close this one in favor of the older. Let's track this issue over there.

Thank you.

**Closed as completed** 2020-01-07 13:14 UTC
Labels: bug, duplicate, help wanted
